development:
  adapter: postgresql
  database: whydontwe
  username: postgres
  password: postgres
  host: localhost

test: &test
  adapter: postgresql
  database: whydontwe
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: whydontwe
  username: postgres
  password: postgres
  host: localhost
